# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92c8d3206790d9a02d8d8a37eb6e6191416d7677d6b849786550a954efc15f6f9343c5914a2c91db78a458ccd295b3c22f2e1ce0b2eae2d3e0b7857b263fdb89

test:
  secret_key_base: 5440cab0f85ccf01b74917f867a4486ab44c9d36060580992cb869fc3d867b726c85d39950293f11459d927b685b33c347a274b3dcda0f4d2ded24019e71445b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
